name: Generate AI Profile

on:
  workflow_dispatch:
    inputs:
      github_user:
        description: GitHub username
        required: true
        type: string
      linkedin_user:
        description: LinkedIn public id/username
        required: true
        type: string
      name:
        description: Display name for the final profile
        required: true
        type: string
      rss_url:
        description: RSS feed URL with your blog posts to analyze writing style
        required: false
        type: string
      rss_name:
        description: Name of the RSS feed
        required: false
        type: string
      important_notes:
        description: Use this to add critical restrictions, annotations, or clarifications about the user that must be considered at all times when interpreting or applying the profile. (250 characters max)
        required: false
        type: string

permissions:
  contents: write

jobs:
  github:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jbarea/my-ai-profile-generator:1.1.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run GitHub analysis
        env:
          GITHUB_TOKEN: ${{ github.token }}
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
        run: |
          python cli.py github "${{ inputs.github_user }}"

      - name: Upload GitHub analysis artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-analysis
          path: github_analysis.json

  linkedin:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jbarea/my-ai-profile-generator:1.1.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run LinkedIn analysis
        env:
          LINKEDIN_LI_AT: ${{ secrets.LINKEDIN_LI_AT }}
          LINKEDIN_JSESSIONID: ${{ secrets.LINKEDIN_JSESSIONID }}
          GITHUB_TOKEN: ${{ github.token }}
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
        run: |
          python cli.py linkedin "${{ inputs.linkedin_user }}"

      - name: Upload LinkedIn analysis artifact
        uses: actions/upload-artifact@v4
        with:
          name: linkedin-analysis
          path: linkedin_analysis.json

  rss:
    runs-on: ubuntu-latest
    if: ${{ inputs.rss_url != '' }}
    container:
      image: quay.io/jbarea/my-ai-profile-generator:1.1.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run RSS analysis
        env:
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
        run: |
          python cli.py rss "${{ inputs.rss_url }}" "${{ inputs.rss_name }}"

      - name: Upload LinkedIn analysis artifact
        uses: actions/upload-artifact@v4
        with:
          name: rss-analysis
          path: rss_analysis.json

  important_notes:
    runs-on: ubuntu-latest
    if: ${{ inputs.important_notes != '' }}
    container:
      image: quay.io/jbarea/my-ai-profile-generator:1.1.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run important notes addition
        run: |
          python cli.py important_notes "${{ inputs.important_notes }}"

      - name: Upload important notes artifact
        uses: actions/upload-artifact@v4
        with:
          name: important-notes
          path: important_notes.json

  merge:
    runs-on: ubuntu-latest
    needs: [github, linkedin, rss, important_notes]
    if: ${{ (needs.github.result == 'success' && needs.linkedin.result == 'success') && (needs.rss.result == 'success' || needs.rss.result == 'skipped') && (needs.important_notes.result == 'success' || needs.important_notes.result == 'skipped') }}
    container:
      image: quay.io/jbarea/my-ai-profile-generator:1.1.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download GitHub analysis
        uses: actions/download-artifact@v4
        with:
          name: github-analysis
          path: .

      - name: Download LinkedIn analysis
        uses: actions/download-artifact@v4
        with:
          name: linkedin-analysis
          path: .
      
      - name: Download important notes
        if: ${{ inputs.important_notes != '' }}
        uses: actions/download-artifact@v4
        with:
          name: important-notes
          path: .

      - name: Download RSS analysis
        if: ${{ inputs.rss_url != '' }}
        uses: actions/download-artifact@v4
        with:
          name: rss-analysis
          path: .

      - name: Place analysis files at repo root
        run: |
          mv -f github-analysis/github_analysis.json . 2>/dev/null || true
          mv -f linkedin-analysis/linkedin_analysis.json . 2>/dev/null || true
          mv -f important-notes/important_notes.json . 2>/dev/null || true
          mv -f rss-analysis/rss_analysis.json . 2>/dev/null || true
          ls -la

      - name: Run merge
        run: |
          python cli.py merge "${{ inputs.name }}"
          ls -la

      - name: Upload final profile artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-profile
          path: MyAIProfile.md

  push:
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download final profile artifact
        uses: actions/download-artifact@v4
        with:
          name: final-profile
          path: .

      - name: Move profile to root
        run: |
          mv -f final-profile/MyAIProfile.md . 2>/dev/null || true
          ls -la

      - name: Commit and push updated profile
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -e
          git config --global --add safe.directory "$PWD"
          if git status --porcelain | grep -q "MyAIProfile.md"; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add MyAIProfile.md
            git commit -m "chore: update MyAIProfile.md [skip ci]" || exit 0
            git push
          else
            echo "No changes to commit."
          fi 